id: P010670
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ2550
  title: ཆོས་དབྱིངས་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ལུང་གི་གཏེར་མཛོད།
  author: ''
  volumes:
    c40b001b922c42bd8e591c8f2d5f75bc:
      image_group_id: I1CZ2729
      title: ''
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
