id: I168B4131
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:49:43+00:00'
last_modified: '2022-06-08T16:41:24.389920+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2550
  title: ཆོས་དབྱིངས་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ལུང་གི་གཏེར་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    45FE:
      image_group_id: I1CZ2729
      title: ''
      total_pages: 426
      order: 1
      base_file: 45FE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
