id: I168B4131
legacy_id: P010670
ocr_import_info:
  bdrc_scan_id: W1CZ2550
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T04:47:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:26:41.690439+00:00'
last_modified: 2022-08-31 03:27:16.069144
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2550
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2550
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་དབྱིངས་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ལུང་གི་གཏེར་མཛོད།
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.6652935684536785
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1CZ2729:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2729
      total_pages: 426
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2729.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6652935684536785
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
